var btn1 = document.querySelector(".btn1")
console.log(btn1)
var btn2 = document.body.querySelector(".btn2")
console.log(btn2)
var btn3=document.body.querySelector(".btn3")
console.log(btn3)
var btn4=document.body.querySelector(".btn4")
console.log(btn4)
var btn5=document.body.querySelector(".btn5")
console.log(btn5)
var item1 = document.querySelector("#item1")
console.log(item1)
var item2 = document.querySelector("#item2")
console.log(item2)
var item3 = document.querySelector("#item3")
console.log(item3)
var item4 = document.querySelector("#item4")
console.log(item4)
var item5 = document.querySelector("#item5")
console.log(item5)
var item6 = document.querySelector("#item6")
console.log(item6)
var item7 = document.querySelector("#item7")
console.log(item7)
var item8 = document.querySelector("#item8")
console.log(item8)
var item9 = document.querySelector("#item9")
console.log(item9)


btn1.addEventListener("click", myFunc1)
function myFunc1(){
btn1.style.color = "#53b778"
btn1.style.borderBottom = "2px solid #53b778"
btn2.style.color = "#606060"
btn2.style.borderBottom = "0px solid #53b778"
btn3.style.color = "#606060"
btn3.style.borderBottom = "0px solid #53b778"
btn4.style.color = "#606060"
btn4.style.borderBottom = "0px solid #53b778"
btn5.style.color = "#606060"
btn5.style.borderBottom = "0px solid #53b778"
item1.style.transition = "all 1s ease"
item1.style.width = "31%"
item1.style.height = "300px"
item1.style.margin = "10px"
item2.style.transition = "all 1s ease"
item2.style.width = "31%"
item2.style.height = "300px"
item2.style.margin = "10px"
item3.style.transition = "all 1s ease"
item3.style.width = "31%"
item3.style.height = "300px"
item3.style.margin = "10px"
item4.style.transition = "all 1s ease"
item4.style.width = "31%"
item4.style.height = "300px"
item4.style.margin = "10px"
item5.style.transition = "all 1s ease"
item5.style.width = "31%"
item5.style.height = "300px"
item5.style.margin = "10px"
item6.style.transition = "all 1s ease"
item6.style.width = "31%"
item6.style.height = "300px"
item6.style.margin = "10px"
item7.style.transition = "all 1s ease"
item7.style.width = "31%"
item7.style.height = "300px"
item7.style.margin = "10px"
item8.style.transition = "all 1s ease"
item8.style.width = "31%"
item8.style.height = "300px"
item8.style.margin = "10px"
item9.style.transition = "all 1s ease"
item9.style.width = "31%"
item9.style.height = "300px"
item9.style.margin = "10px"
}

btn2.addEventListener("click", myFunc2)
function myFunc2(){
btn1.style.color = "#606060"
btn1.style.borderBottom = "0px solid #53b778"
btn2.style.color = "#53b778"
btn2.style.borderBottom = "2px solid #53b778"
btn3.style.color = "#606060"
btn3.style.borderBottom = "0px solid #53b778"
btn4.style.color = "#606060"
btn4.style.borderBottom = "0px solid #53b778"
btn5.style.color = "#606060"
btn5.style.borderBottom = "0px solid #53b778"
item1.style.transition = "all 1s ease"
item1.style.width = "31%"
item1.style.height = "300px"
item1.style.margin = "10px"
item3.style.margin = "0px"
item2.style.transition = "all 1s ease"
item2.style.width = "31%"
item2.style.height = "300px"
item2.style.margin = "10px"
item3.style.transition = "all 1s ease"
item3.style.width = "0px"
item3.style.height = "0px"
item3.style.margin = "0px"
item4.style.transition = "all 1s ease"
item4.style.width = "0px"
item4.style.height = "0px"
item4.style.margin = "0px"
item5.style.transition = "all 1s ease"
item5.style.width = "31%"
item5.style.height = "300px"
item5.style.margin = "10px"
item6.style.transition = "all 1s ease"
item6.style.width = "0px"
item6.style.height = "0px"
item6.style.margin = "0px"
item7.style.transition = "all 1s ease"
item7.style.width = "0px"
item7.style.height = "0px"
item7.style.margin = "0px"
item8.style.transition = "all 1s ease"
item8.style.width = "0px"
item8.style.height = "0px"
item8.style.margin = "0px"
item9.style.transition = "all 1s ease"
item9.style.width = "0px"
item9.style.height = "0px"
item9.style.margin = "0px"
}

btn3.addEventListener("click", myFunc3)
function myFunc3(){
btn1.style.color = "#606060"
btn1.style.borderBottom = "0px solid #53b778"
btn2.style.color = "#606060"
btn2.style.borderBottom = "0px solid #53b778"
btn3.style.color = "#53b778"
btn3.style.borderBottom = "2px solid #53b778"
btn4.style.color = "#606060"
btn4.style.borderBottom = "0px solid #53b778"
btn5.style.color = "#606060"
btn5.style.borderBottom = "0px solid #53b778"
item1.style.transition = "all 1s ease"
item1.style.width = "0px"
item1.style.height = "0px"
item1.style.margin = "0px"
item2.style.transition = "all 1s ease"
item2.style.width = "0px"
item2.style.height = "0px"
item3.style.transition = "all 1s ease"
item3.style.width = "31%"
item3.style.height = "300px"
item3.style.margin = "10px"
item4.style.transition = "all 1s ease"
item4.style.width = "31%"
item4.style.height = "300px"
item4.style.margin = "10px"
item5.style.transition = "all 1s ease"
item5.style.width = "0px"
item5.style.height = "0px"
item5.style.margin = "0px"
item6.style.transition = "all 1s ease"
item6.style.width = "0px"
item6.style.height = "0px"
item6.style.margin = "0px"
item7.style.transition = "all 1s ease"
item7.style.width = "0px"
item7.style.height = "0px"
item7.style.margin = "0px"
item8.style.transition = "all 1s ease"
item8.style.width = "0px"
item8.style.height = "0px"
item8.style.margin = "0px"
item9.style.transition = "all 1s ease"
item9.style.width = "0px"
item9.style.height = "0px"
item9.style.margin = "0px"
}

btn4.addEventListener("click", myFunc4)
function myFunc4(){
btn1.style.color = "#606060"
btn1.style.borderBottom = "0px solid #53b778"
btn2.style.color = "#606060"
btn2.style.borderBottom = "0px solid #53b778"
btn3.style.color = "#606060"
btn3.style.borderBottom = "0px solid #53b778"
btn4.style.color = "#53b778"
btn4.style.borderBottom = "2px solid #53b778"
btn5.style.color = "#606060"
btn5.style.borderBottom = "0px solid #53b778"
item1.style.transition = "all 1s ease"
item1.style.width = "0px"
item1.style.height = "0px"
item1.style.margin = "0px"
item2.style.transition = "all 1s ease"
item2.style.width = "0px"
item2.style.height = "0px"
item3.style.transition = "all 1s ease"
item3.style.width = "0px"
item3.style.height = "0px"
item3.style.margin = "0px"
item4.style.transition = "all 1s ease"
item4.style.width = "0px"
item4.style.height = "0px"
item4.style.margin = "0px"
item5.style.transition = "all 1s ease"
item5.style.width = "0px"
item5.style.height = "0px"
item5.style.margin = "0px"
item6.style.transition = "all 1s ease"
item6.style.width = "31%"
item6.style.height = "300px"
item6.style.margin = "10px"
item7.style.transition = "all 1s ease"
item7.style.width = "31%"
item7.style.height = "300px"
item7.style.margin = "10px"
item8.style.transition = "all 1s ease"
item8.style.width = "0px"
item8.style.height = "0px"
item8.style.margin = "0px"
item9.style.transition = "all 1s ease"
item9.style.width = "0px"
item9.style.height = "0px"
item9.style.margin = "0px"
}


btn5.addEventListener("click", myFunc5)
function myFunc5(){
btn1.style.color = "#606060"
btn1.style.borderBottom = "0px solid #53b778"
btn2.style.color = "#606060"
btn2.style.borderBottom = "0px solid #53b778"
btn3.style.color = "#606060"
btn3.style.borderBottom = "0px solid #53b778"
btn4.style.color = "#606060"
btn4.style.borderBottom = "0px solid #53b778"
btn5.style.color = "#53b778"
btn5.style.borderBottom = "2px solid #53b778"
item1.style.transition = "all 1s ease"
item1.style.width = "0px"
item1.style.height = "0px"
item1.style.margin = "0px"
item2.style.transition = "all 1s ease"
item2.style.width = "0px"
item2.style.height = "0px"
item3.style.transition = "all 1s ease"
item3.style.width = "0px"
item3.style.height = "0px"
item3.style.margin = "0px"
item4.style.transition = "all 1s ease"
item4.style.width = "0px"
item4.style.height = "0px"
item4.style.margin = "0px"
item5.style.transition = "all 1s ease"
item5.style.width = "0px"
item5.style.height = "0px"
item5.style.margin = "0px"
item6.style.transition = "all 1s ease"
item6.style.width = "0px"
item6.style.height = "0px"
item6.style.margin = "0px"
item7.style.transition = "all 1s ease"
item7.style.width = "0px"
item7.style.height = "0px"
item7.style.margin = "0px"
item8.style.transition = "all 1s ease"
item8.style.width = "31%"
item8.style.height = "300px"
item8.style.margin = "10px"
item9.style.transition = "all 1s ease"
item9.style.width = "31%"
item9.style.height = "300px"
item9.style.margin = "10px"
}